export interface Photo {
  id: string;
  url: string;         // full-res or preview (~1200px) — used in lightbox
  thumbnailUrl?: string; // small (~400px) — used in grids; falls back to url
  alt: string;
  event: string;   // matches Event.id (e.g. 'ceremony', not 'The Ceremony')
  date: string;
  people?: string[];
  isHighlight?: boolean;
}

export interface Album {
  id: string;
  title: string;
  coverUrl: string;
  eventId: string;     // which event this album belongs to
  photoIds: string[];  // explicit photo list
}

export interface Event {
  id: string;
  title: string;
  photoCount: number;
  coverUrl: string;      // used in event detail hero + home highlights
  listCoverUrl?: string; // overrides coverUrl on the events list card only
  date: string;
  likes: number;
}

export const EVENTS: Event[] = [
  {
    id: 'engagement',
    title: 'Engagement',
    photoCount: 48,
    coverUrl: '/photos/engagement/preview/MPPF-186.jpg',
    date: 'Dec 2, 2025',
    likes: 45
  },
  {
    id: 'prewedding',
    title: 'Pre-Wedding',
    photoCount: 35,
    coverUrl: '/photos/prewedding/preview/IMG_5404.jpg',
    date: 'Jan 15–17, 2026',
    likes: 67
  },
  {
    id: 'haldi',
    title: 'Haldi',
    photoCount: 40,
    coverUrl: '/photos/haldi/preview/shruti_MPPF-10.jpg',
    date: 'Feb 8, 2026',
    likes: 23
  },
  {
    id: 'ceremony',
    title: 'Wedding Ceremony',
    photoCount: 55,
    coverUrl: '/photos/ceremony/preview/MPPF-2.jpg',
    listCoverUrl: '/photos/ceremony/preview/MPPF-372.jpg',
    date: 'Feb 10, 2026',
    likes: 89
  },
  {
    id: 'reception',
    title: 'Reception',
    photoCount: 33,
    coverUrl: '/photos/reception/preview/MPPF-388.jpg',
    date: 'Feb 10, 2026',
    likes: 54
  }
];

export const PHOTOS: Photo[] = [
  // Engagement
  {
    id: 'eng-1',
    url: '/photos/engagement/preview/MPPF-64.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-64.jpg',
    alt: 'Engagement photo 1',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-2',
    url: '/photos/engagement/preview/MPPF-70.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-70.jpg',
    alt: 'Engagement photo 2',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-3',
    url: '/photos/engagement/preview/MPPF-72.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-72.jpg',
    alt: 'Engagement photo 3',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-4',
    url: '/photos/engagement/preview/MPPF-73.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-73.jpg',
    alt: 'Engagement photo 4',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-5',
    url: '/photos/engagement/preview/MPPF-76.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-76.jpg',
    alt: 'Engagement photo 5',
    event: 'engagement',
    date: 'Dec 2, 2025',
    isHighlight: true
  },
  {
    id: 'eng-6',
    url: '/photos/engagement/preview/MPPF-79.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-79.jpg',
    alt: 'Engagement photo 6',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-7',
    url: '/photos/engagement/preview/MPPF-88.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-88.jpg',
    alt: 'Engagement photo 7',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-8',
    url: '/photos/engagement/preview/MPPF-92.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-92.jpg',
    alt: 'Engagement photo 8',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-9',
    url: '/photos/engagement/preview/MPPF-93.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-93.jpg',
    alt: 'Engagement photo 9',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-10',
    url: '/photos/engagement/preview/MPPF-94.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-94.jpg',
    alt: 'Engagement photo 10',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-11',
    url: '/photos/engagement/preview/MPPF-95.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-95.jpg',
    alt: 'Engagement photo 11',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-12',
    url: '/photos/engagement/preview/MPPF-96.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-96.jpg',
    alt: 'Engagement photo 12',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-13',
    url: '/photos/engagement/preview/MPPF-97.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-97.jpg',
    alt: 'Engagement photo 13',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-14',
    url: '/photos/engagement/preview/MPPF-98.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-98.jpg',
    alt: 'Engagement photo 14',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-15',
    url: '/photos/engagement/preview/MPPF-99.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-99.jpg',
    alt: 'Engagement photo 15',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-16',
    url: '/photos/engagement/preview/MPPF-102.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-102.jpg',
    alt: 'Engagement photo 16',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-17',
    url: '/photos/engagement/preview/MPPF-103.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-103.jpg',
    alt: 'Engagement photo 17',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-18',
    url: '/photos/engagement/preview/MPPF-104.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-104.jpg',
    alt: 'Engagement photo 18',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-19',
    url: '/photos/engagement/preview/MPPF-105.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-105.jpg',
    alt: 'Engagement photo 19',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-20',
    url: '/photos/engagement/preview/MPPF-106.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-106.jpg',
    alt: 'Engagement photo 20',
    event: 'engagement',
    date: 'Dec 2, 2025',
    isHighlight: true
  },
  {
    id: 'eng-21',
    url: '/photos/engagement/preview/MPPF-112.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-112.jpg',
    alt: 'Engagement photo 21',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-22',
    url: '/photos/engagement/preview/MPPF-114.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-114.jpg',
    alt: 'Engagement photo 22',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-23',
    url: '/photos/engagement/preview/MPPF-117.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-117.jpg',
    alt: 'Engagement photo 23',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-24',
    url: '/photos/engagement/preview/MPPF-119.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-119.jpg',
    alt: 'Engagement photo 24',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-25',
    url: '/photos/engagement/preview/MPPF-122.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-122.jpg',
    alt: 'Engagement photo 25',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-26',
    url: '/photos/engagement/preview/MPPF-123.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-123.jpg',
    alt: 'Engagement photo 26',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-27',
    url: '/photos/engagement/preview/MPPF-125.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-125.jpg',
    alt: 'Engagement photo 27',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-28',
    url: '/photos/engagement/preview/MPPF-128.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-128.jpg',
    alt: 'Engagement photo 28',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-29',
    url: '/photos/engagement/preview/MPPF-129.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-129.jpg',
    alt: 'Engagement photo 29',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-30',
    url: '/photos/engagement/preview/MPPF-131.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-131.jpg',
    alt: 'Engagement photo 30',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-31',
    url: '/photos/engagement/preview/MPPF-133.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-133.jpg',
    alt: 'Engagement photo 31',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-32',
    url: '/photos/engagement/preview/MPPF-136.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-136.jpg',
    alt: 'Engagement photo 32',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-33',
    url: '/photos/engagement/preview/MPPF-137.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-137.jpg',
    alt: 'Engagement photo 33',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-34',
    url: '/photos/engagement/preview/MPPF-139.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-139.jpg',
    alt: 'Engagement photo 34',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-35',
    url: '/photos/engagement/preview/MPPF-140.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-140.jpg',
    alt: 'Engagement photo 35',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-36',
    url: '/photos/engagement/preview/MPPF-141.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-141.jpg',
    alt: 'Engagement photo 36',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-37',
    url: '/photos/engagement/preview/MPPF-142.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-142.jpg',
    alt: 'Engagement photo 37',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-38',
    url: '/photos/engagement/preview/MPPF-143.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-143.jpg',
    alt: 'Engagement photo 38',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-39',
    url: '/photos/engagement/preview/MPPF-146.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-146.jpg',
    alt: 'Engagement photo 39',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-40',
    url: '/photos/engagement/preview/MPPF-147.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-147.jpg',
    alt: 'Engagement photo 40',
    event: 'engagement',
    date: 'Dec 2, 2025',
    isHighlight: true
  },
  {
    id: 'eng-41',
    url: '/photos/engagement/preview/MPPF-148.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-148.jpg',
    alt: 'Engagement photo 41',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-42',
    url: '/photos/engagement/preview/MPPF-149.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-149.jpg',
    alt: 'Engagement photo 42',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-43',
    url: '/photos/engagement/preview/MPPF-182.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-182.jpg',
    alt: 'Engagement photo 43',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-44',
    url: '/photos/engagement/preview/MPPF-186.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-186.jpg',
    alt: 'Engagement photo 44',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-45',
    url: '/photos/engagement/preview/MPPF-202.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-202.jpg',
    alt: 'Engagement photo 45',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-46',
    url: '/photos/engagement/preview/MPPF-204.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-204.jpg',
    alt: 'Engagement photo 46',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-47',
    url: '/photos/engagement/preview/MPPF-205.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-205.jpg',
    alt: 'Engagement photo 47',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },
  {
    id: 'eng-48',
    url: '/photos/engagement/preview/MPPF-206.jpg',
    thumbnailUrl: '/photos/engagement/thumbs/MPPF-206.jpg',
    alt: 'Engagement photo 48',
    event: 'engagement',
    date: 'Dec 2, 2025',
  },

  // Pre-Wedding
  {
    id: 'pw-1',
    url: '/photos/prewedding/preview/IMG_5404.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/IMG_5404.jpg',
    alt: 'Pre-wedding photo 1',
    event: 'prewedding',
    date: 'Jan 15, 2026',
    isHighlight: true
  },
  {
    id: 'pw-2',
    url: '/photos/prewedding/preview/MPPF-103.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-103.jpg',
    alt: 'Pre-wedding photo 2',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-3',
    url: '/photos/prewedding/preview/MPPF-105.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-105.jpg',
    alt: 'Pre-wedding photo 3',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-4',
    url: '/photos/prewedding/preview/MPPF-107.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-107.jpg',
    alt: 'Pre-wedding photo 4',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-5',
    url: '/photos/prewedding/preview/MPPF-115.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-115.jpg',
    alt: 'Pre-wedding photo 5',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-6',
    url: '/photos/prewedding/preview/MPPF-116.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-116.jpg',
    alt: 'Pre-wedding photo 6',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-7',
    url: '/photos/prewedding/preview/MPPF-119.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-119.jpg',
    alt: 'Pre-wedding photo 7',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-8',
    url: '/photos/prewedding/preview/MPPF-132.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-132.jpg',
    alt: 'Pre-wedding photo 8',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-9',
    url: '/photos/prewedding/preview/MPPF-135.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-135.jpg',
    alt: 'Pre-wedding photo 9',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-10',
    url: '/photos/prewedding/preview/MPPF-136.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-136.jpg',
    alt: 'Pre-wedding photo 10',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-11',
    url: '/photos/prewedding/preview/MPPF-137.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-137.jpg',
    alt: 'Pre-wedding photo 11',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-12',
    url: '/photos/prewedding/preview/MPPF-16.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-16.jpg',
    alt: 'Pre-wedding photo 12',
    event: 'prewedding',
    date: 'Jan 15, 2026',
    isHighlight: true
  },
  {
    id: 'pw-13',
    url: '/photos/prewedding/preview/MPPF-18.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-18.jpg',
    alt: 'Pre-wedding photo 13',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-14',
    url: '/photos/prewedding/preview/MPPF-23.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-23.jpg',
    alt: 'Pre-wedding photo 14',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-15',
    url: '/photos/prewedding/preview/MPPF-42.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-42.jpg',
    alt: 'Pre-wedding photo 15',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-16',
    url: '/photos/prewedding/preview/MPPF-43.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-43.jpg',
    alt: 'Pre-wedding photo 16',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-17',
    url: '/photos/prewedding/preview/MPPF-45.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-45.jpg',
    alt: 'Pre-wedding photo 17',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-18',
    url: '/photos/prewedding/preview/MPPF-47.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-47.jpg',
    alt: 'Pre-wedding photo 18',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-19',
    url: '/photos/prewedding/preview/MPPF-48.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-48.jpg',
    alt: 'Pre-wedding photo 19',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-20',
    url: '/photos/prewedding/preview/MPPF-49.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-49.jpg',
    alt: 'Pre-wedding photo 20',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-21',
    url: '/photos/prewedding/preview/MPPF-53.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-53.jpg',
    alt: 'Pre-wedding photo 21',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-22',
    url: '/photos/prewedding/preview/MPPF-59.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-59.jpg',
    alt: 'Pre-wedding photo 22',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-23',
    url: '/photos/prewedding/preview/MPPF-61.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-61.jpg',
    alt: 'Pre-wedding photo 23',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-24',
    url: '/photos/prewedding/preview/MPPF-64.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-64.jpg',
    alt: 'Pre-wedding photo 24',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-25',
    url: '/photos/prewedding/preview/MPPF-65.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-65.jpg',
    alt: 'Pre-wedding photo 25',
    event: 'prewedding',
    date: 'Jan 15, 2026',
    isHighlight: true
  },
  {
    id: 'pw-26',
    url: '/photos/prewedding/preview/MPPF-67.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-67.jpg',
    alt: 'Pre-wedding photo 26',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-27',
    url: '/photos/prewedding/preview/MPPF-68.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-68.jpg',
    alt: 'Pre-wedding photo 27',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-28',
    url: '/photos/prewedding/preview/MPPF-71.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-71.jpg',
    alt: 'Pre-wedding photo 28',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-29',
    url: '/photos/prewedding/preview/MPPF-72.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-72.jpg',
    alt: 'Pre-wedding photo 29',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-30',
    url: '/photos/prewedding/preview/MPPF-77.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-77.jpg',
    alt: 'Pre-wedding photo 30',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-31',
    url: '/photos/prewedding/preview/MPPF-79.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-79.jpg',
    alt: 'Pre-wedding photo 31',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-32',
    url: '/photos/prewedding/preview/MPPF-85.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-85.jpg',
    alt: 'Pre-wedding photo 32',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-33',
    url: '/photos/prewedding/preview/MPPF-86.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-86.jpg',
    alt: 'Pre-wedding photo 33',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-34',
    url: '/photos/prewedding/preview/MPPF-87.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-87.jpg',
    alt: 'Pre-wedding photo 34',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },
  {
    id: 'pw-35',
    url: '/photos/prewedding/preview/MPPF-99.jpg',
    thumbnailUrl: '/photos/prewedding/thumbs/MPPF-99.jpg',
    alt: 'Pre-wedding photo 35',
    event: 'prewedding',
    date: 'Jan 15, 2026',
  },

  // Haldi
  {
    id: 'hal-1',
    url: '/photos/haldi/preview/shruti_MPPF-10.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-10.jpg',
    alt: 'Haldi photo 1',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
    isHighlight: true
  },
  {
    id: 'hal-2',
    url: '/photos/haldi/preview/shruti_MPPF-109.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-109.jpg',
    alt: 'Haldi photo 2',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-3',
    url: '/photos/haldi/preview/shruti_MPPF-110.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-110.jpg',
    alt: 'Haldi photo 3',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-4',
    url: '/photos/haldi/preview/shruti_MPPF-111.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-111.jpg',
    alt: 'Haldi photo 4',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-5',
    url: '/photos/haldi/preview/shruti_MPPF-112.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-112.jpg',
    alt: 'Haldi photo 5',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-6',
    url: '/photos/haldi/preview/shruti_MPPF-138.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-138.jpg',
    alt: 'Haldi photo 6',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-7',
    url: '/photos/haldi/preview/shruti_MPPF-15.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-15.jpg',
    alt: 'Haldi photo 7',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
    isHighlight: true
  },
  {
    id: 'hal-8',
    url: '/photos/haldi/preview/shruti_MPPF-16.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-16.jpg',
    alt: 'Haldi photo 8',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-9',
    url: '/photos/haldi/preview/shruti_MPPF-21.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-21.jpg',
    alt: 'Haldi photo 9',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-10',
    url: '/photos/haldi/preview/shruti_MPPF-23.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-23.jpg',
    alt: 'Haldi photo 10',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-11',
    url: '/photos/haldi/preview/shruti_MPPF-26.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-26.jpg',
    alt: 'Haldi photo 11',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-12',
    url: '/photos/haldi/preview/shruti_MPPF-3.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-3.jpg',
    alt: 'Haldi photo 12',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-13',
    url: '/photos/haldi/preview/shruti_MPPF-4.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-4.jpg',
    alt: 'Haldi photo 13',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
    isHighlight: true
  },
  {
    id: 'hal-14',
    url: '/photos/haldi/preview/shruti_MPPF-45.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-45.jpg',
    alt: 'Haldi photo 14',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-15',
    url: '/photos/haldi/preview/shruti_MPPF-75.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-75.jpg',
    alt: 'Haldi photo 15',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-16',
    url: '/photos/haldi/preview/shruti_MPPF-76.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-76.jpg',
    alt: 'Haldi photo 16',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-17',
    url: '/photos/haldi/preview/shruti_MPPF-78.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-78.jpg',
    alt: 'Haldi photo 17',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-18',
    url: '/photos/haldi/preview/shruti_MPPF-8.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-8.jpg',
    alt: 'Haldi photo 18',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-19',
    url: '/photos/haldi/preview/shruti_MPPF-9.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF-9.jpg',
    alt: 'Haldi photo 19',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
    isHighlight: true
  },
  {
    id: 'hal-20',
    url: '/photos/haldi/preview/shruti_MPPF.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/shruti_MPPF.jpg',
    alt: 'Haldi photo 20',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Shruti'],
  },
  {
    id: 'hal-21',
    url: '/photos/haldi/preview/umesh_MPPF-159.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-159.jpg',
    alt: 'Haldi photo 21',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-22',
    url: '/photos/haldi/preview/umesh_MPPF-160.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-160.jpg',
    alt: 'Haldi photo 22',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-23',
    url: '/photos/haldi/preview/umesh_MPPF-161.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-161.jpg',
    alt: 'Haldi photo 23',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-24',
    url: '/photos/haldi/preview/umesh_MPPF-184.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-184.jpg',
    alt: 'Haldi photo 24',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-25',
    url: '/photos/haldi/preview/umesh_MPPF-24.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-24.jpg',
    alt: 'Haldi photo 25',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
    isHighlight: true
  },
  {
    id: 'hal-26',
    url: '/photos/haldi/preview/umesh_MPPF-29.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-29.jpg',
    alt: 'Haldi photo 26',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-27',
    url: '/photos/haldi/preview/umesh_MPPF-32.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-32.jpg',
    alt: 'Haldi photo 27',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-28',
    url: '/photos/haldi/preview/umesh_MPPF-35.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-35.jpg',
    alt: 'Haldi photo 28',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-29',
    url: '/photos/haldi/preview/umesh_MPPF-37.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-37.jpg',
    alt: 'Haldi photo 29',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-30',
    url: '/photos/haldi/preview/umesh_MPPF-45.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-45.jpg',
    alt: 'Haldi photo 30',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-31',
    url: '/photos/haldi/preview/umesh_MPPF-47.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-47.jpg',
    alt: 'Haldi photo 31',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
    isHighlight: true
  },
  {
    id: 'hal-32',
    url: '/photos/haldi/preview/umesh_MPPF-49.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-49.jpg',
    alt: 'Haldi photo 32',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-33',
    url: '/photos/haldi/preview/umesh_MPPF-50.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-50.jpg',
    alt: 'Haldi photo 33',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-34',
    url: '/photos/haldi/preview/umesh_MPPF-51.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-51.jpg',
    alt: 'Haldi photo 34',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-35',
    url: '/photos/haldi/preview/umesh_MPPF-52.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-52.jpg',
    alt: 'Haldi photo 35',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-36',
    url: '/photos/haldi/preview/umesh_MPPF-53.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-53.jpg',
    alt: 'Haldi photo 36',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-37',
    url: '/photos/haldi/preview/umesh_MPPF-64.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-64.jpg',
    alt: 'Haldi photo 37',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
    isHighlight: true
  },
  {
    id: 'hal-38',
    url: '/photos/haldi/preview/umesh_MPPF-65.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-65.jpg',
    alt: 'Haldi photo 38',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-39',
    url: '/photos/haldi/preview/umesh_MPPF-81.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-81.jpg',
    alt: 'Haldi photo 39',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },
  {
    id: 'hal-40',
    url: '/photos/haldi/preview/umesh_MPPF-83.jpg',
    thumbnailUrl: '/photos/haldi/thumbs/umesh_MPPF-83.jpg',
    alt: 'Haldi photo 40',
    event: 'haldi',
    date: 'Feb 8, 2026',
    people: ['Umesh'],
  },

  // Ceremony
  {
    id: 'cer-1',
    url: '/photos/ceremony/preview/MPPF-2.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-2.jpg',
    alt: 'Wedding ceremony photo 1',
    event: 'ceremony',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'cer-2',
    url: '/photos/ceremony/preview/MPPF-3.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-3.jpg',
    alt: 'Wedding ceremony photo 2',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-3',
    url: '/photos/ceremony/preview/MPPF-4.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-4.jpg',
    alt: 'Wedding ceremony photo 3',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-4',
    url: '/photos/ceremony/preview/MPPF-8.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-8.jpg',
    alt: 'Wedding ceremony photo 4',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-5',
    url: '/photos/ceremony/preview/MPPF-11.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-11.jpg',
    alt: 'Wedding ceremony photo 5',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-6',
    url: '/photos/ceremony/preview/MPPF-12.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-12.jpg',
    alt: 'Wedding ceremony photo 6',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-7',
    url: '/photos/ceremony/preview/MPPF-13.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-13.jpg',
    alt: 'Wedding ceremony photo 7',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-8',
    url: '/photos/ceremony/preview/MPPF-15.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-15.jpg',
    alt: 'Wedding ceremony photo 8',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-9',
    url: '/photos/ceremony/preview/MPPF-21.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-21.jpg',
    alt: 'Wedding ceremony photo 9',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-10',
    url: '/photos/ceremony/preview/MPPF-24.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-24.jpg',
    alt: 'Wedding ceremony photo 10',
    event: 'ceremony',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'cer-11',
    url: '/photos/ceremony/preview/MPPF-25.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-25.jpg',
    alt: 'Wedding ceremony photo 11',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-12',
    url: '/photos/ceremony/preview/MPPF-26.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-26.jpg',
    alt: 'Wedding ceremony photo 12',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-13',
    url: '/photos/ceremony/preview/MPPF-28.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-28.jpg',
    alt: 'Wedding ceremony photo 13',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-14',
    url: '/photos/ceremony/preview/MPPF-30.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-30.jpg',
    alt: 'Wedding ceremony photo 14',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-15',
    url: '/photos/ceremony/preview/MPPF-31.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-31.jpg',
    alt: 'Wedding ceremony photo 15',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-16',
    url: '/photos/ceremony/preview/MPPF-36.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-36.jpg',
    alt: 'Wedding ceremony photo 16',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-17',
    url: '/photos/ceremony/preview/MPPF-38.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-38.jpg',
    alt: 'Wedding ceremony photo 17',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-18',
    url: '/photos/ceremony/preview/MPPF-40.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-40.jpg',
    alt: 'Wedding ceremony photo 18',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-19',
    url: '/photos/ceremony/preview/MPPF-42.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-42.jpg',
    alt: 'Wedding ceremony photo 19',
    event: 'ceremony',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'cer-20',
    url: '/photos/ceremony/preview/MPPF-43.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-43.jpg',
    alt: 'Wedding ceremony photo 20',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-21',
    url: '/photos/ceremony/preview/MPPF-46.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-46.jpg',
    alt: 'Wedding ceremony photo 21',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-22',
    url: '/photos/ceremony/preview/MPPF-55.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-55.jpg',
    alt: 'Wedding ceremony photo 22',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-23',
    url: '/photos/ceremony/preview/MPPF-60.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-60.jpg',
    alt: 'Wedding ceremony photo 23',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-24',
    url: '/photos/ceremony/preview/MPPF-61.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-61.jpg',
    alt: 'Wedding ceremony photo 24',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-25',
    url: '/photos/ceremony/preview/MPPF-65.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-65.jpg',
    alt: 'Wedding ceremony photo 25',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-26',
    url: '/photos/ceremony/preview/MPPF-69.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-69.jpg',
    alt: 'Wedding ceremony photo 26',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-27',
    url: '/photos/ceremony/preview/MPPF-71.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-71.jpg',
    alt: 'Wedding ceremony photo 27',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-28',
    url: '/photos/ceremony/preview/MPPF-75.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-75.jpg',
    alt: 'Wedding ceremony photo 28',
    event: 'ceremony',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'cer-29',
    url: '/photos/ceremony/preview/MPPF-76.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-76.jpg',
    alt: 'Wedding ceremony photo 29',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-30',
    url: '/photos/ceremony/preview/MPPF-77.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-77.jpg',
    alt: 'Wedding ceremony photo 30',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-31',
    url: '/photos/ceremony/preview/MPPF-103.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-103.jpg',
    alt: 'Wedding ceremony photo 31',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-32',
    url: '/photos/ceremony/preview/MPPF-107.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-107.jpg',
    alt: 'Wedding ceremony photo 32',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-33',
    url: '/photos/ceremony/preview/MPPF-108.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-108.jpg',
    alt: 'Wedding ceremony photo 33',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-34',
    url: '/photos/ceremony/preview/MPPF-110.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-110.jpg',
    alt: 'Wedding ceremony photo 34',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-35',
    url: '/photos/ceremony/preview/MPPF-123.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-123.jpg',
    alt: 'Wedding ceremony photo 35',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-36',
    url: '/photos/ceremony/preview/MPPF-124.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-124.jpg',
    alt: 'Wedding ceremony photo 36',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-37',
    url: '/photos/ceremony/preview/MPPF-130.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-130.jpg',
    alt: 'Wedding ceremony photo 37',
    event: 'ceremony',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'cer-38',
    url: '/photos/ceremony/preview/MPPF-164.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-164.jpg',
    alt: 'Wedding ceremony photo 38',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-39',
    url: '/photos/ceremony/preview/MPPF-182.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-182.jpg',
    alt: 'Wedding ceremony photo 39',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-40',
    url: '/photos/ceremony/preview/MPPF-220.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-220.jpg',
    alt: 'Wedding ceremony photo 40',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-41',
    url: '/photos/ceremony/preview/MPPF-222.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-222.jpg',
    alt: 'Wedding ceremony photo 41',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-42',
    url: '/photos/ceremony/preview/MPPF-227.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-227.jpg',
    alt: 'Wedding ceremony photo 42',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-43',
    url: '/photos/ceremony/preview/MPPF-229.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-229.jpg',
    alt: 'Wedding ceremony photo 43',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-44',
    url: '/photos/ceremony/preview/MPPF-231.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-231.jpg',
    alt: 'Wedding ceremony photo 44',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-45',
    url: '/photos/ceremony/preview/MPPF-253.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-253.jpg',
    alt: 'Wedding ceremony photo 45',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-46',
    url: '/photos/ceremony/preview/MPPF-264.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-264.jpg',
    alt: 'Wedding ceremony photo 46',
    event: 'ceremony',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'cer-47',
    url: '/photos/ceremony/preview/MPPF-265.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-265.jpg',
    alt: 'Wedding ceremony photo 47',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-48',
    url: '/photos/ceremony/preview/MPPF-267.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-267.jpg',
    alt: 'Wedding ceremony photo 48',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-49',
    url: '/photos/ceremony/preview/MPPF-283.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-283.jpg',
    alt: 'Wedding ceremony photo 49',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-50',
    url: '/photos/ceremony/preview/MPPF-313.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-313.jpg',
    alt: 'Wedding ceremony photo 50',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-51',
    url: '/photos/ceremony/preview/MPPF-335.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-335.jpg',
    alt: 'Wedding ceremony photo 51',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-52',
    url: '/photos/ceremony/preview/MPPF-338.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-338.jpg',
    alt: 'Wedding ceremony photo 52',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-53',
    url: '/photos/ceremony/preview/MPPF-346.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-346.jpg',
    alt: 'Wedding ceremony photo 53',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-54',
    url: '/photos/ceremony/preview/MPPF-349.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-349.jpg',
    alt: 'Wedding ceremony photo 54',
    event: 'ceremony',
    date: 'Feb 10, 2026',
  },
  {
    id: 'cer-55',
    url: '/photos/ceremony/preview/MPPF-372.jpg',
    thumbnailUrl: '/photos/ceremony/thumbs/MPPF-372.jpg',
    alt: 'Wedding ceremony photo 55',
    event: 'ceremony',
    date: 'Feb 10, 2026',
    isHighlight: true
  },

  // Reception
  {
    id: 'rec-1',
    url: '/photos/reception/preview/MPPF-388.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-388.jpg',
    alt: 'Reception photo 1',
    event: 'reception',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'rec-2',
    url: '/photos/reception/preview/MPPF-389.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-389.jpg',
    alt: 'Reception photo 2',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-3',
    url: '/photos/reception/preview/MPPF-391.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-391.jpg',
    alt: 'Reception photo 3',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-4',
    url: '/photos/reception/preview/MPPF-392.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-392.jpg',
    alt: 'Reception photo 4',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-5',
    url: '/photos/reception/preview/MPPF-396.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-396.jpg',
    alt: 'Reception photo 5',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-6',
    url: '/photos/reception/preview/MPPF-397.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-397.jpg',
    alt: 'Reception photo 6',
    event: 'reception',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'rec-7',
    url: '/photos/reception/preview/MPPF-398.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-398.jpg',
    alt: 'Reception photo 7',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-8',
    url: '/photos/reception/preview/MPPF-399.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-399.jpg',
    alt: 'Reception photo 8',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-9',
    url: '/photos/reception/preview/MPPF-401.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-401.jpg',
    alt: 'Reception photo 9',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-10',
    url: '/photos/reception/preview/MPPF-405.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-405.jpg',
    alt: 'Reception photo 10',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-11',
    url: '/photos/reception/preview/MPPF-409.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-409.jpg',
    alt: 'Reception photo 11',
    event: 'reception',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'rec-12',
    url: '/photos/reception/preview/MPPF-443.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-443.jpg',
    alt: 'Reception photo 12',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-13',
    url: '/photos/reception/preview/MPPF-444.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-444.jpg',
    alt: 'Reception photo 13',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-14',
    url: '/photos/reception/preview/MPPF-445.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-445.jpg',
    alt: 'Reception photo 14',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-15',
    url: '/photos/reception/preview/MPPF-446.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-446.jpg',
    alt: 'Reception photo 15',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-16',
    url: '/photos/reception/preview/MPPF-447.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-447.jpg',
    alt: 'Reception photo 16',
    event: 'reception',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'rec-17',
    url: '/photos/reception/preview/MPPF-448.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-448.jpg',
    alt: 'Reception photo 17',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-18',
    url: '/photos/reception/preview/MPPF-449.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-449.jpg',
    alt: 'Reception photo 18',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-19',
    url: '/photos/reception/preview/MPPF-450.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-450.jpg',
    alt: 'Reception photo 19',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-20',
    url: '/photos/reception/preview/MPPF-451.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-451.jpg',
    alt: 'Reception photo 20',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-21',
    url: '/photos/reception/preview/MPPF-452.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-452.jpg',
    alt: 'Reception photo 21',
    event: 'reception',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'rec-22',
    url: '/photos/reception/preview/MPPF-453.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-453.jpg',
    alt: 'Reception photo 22',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-23',
    url: '/photos/reception/preview/MPPF-454.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-454.jpg',
    alt: 'Reception photo 23',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-24',
    url: '/photos/reception/preview/MPPF-455.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-455.jpg',
    alt: 'Reception photo 24',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-25',
    url: '/photos/reception/preview/MPPF-456.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-456.jpg',
    alt: 'Reception photo 25',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-26',
    url: '/photos/reception/preview/MPPF-457.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-457.jpg',
    alt: 'Reception photo 26',
    event: 'reception',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'rec-27',
    url: '/photos/reception/preview/MPPF-458.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-458.jpg',
    alt: 'Reception photo 27',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-28',
    url: '/photos/reception/preview/MPPF-459.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-459.jpg',
    alt: 'Reception photo 28',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-29',
    url: '/photos/reception/preview/MPPF-460.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-460.jpg',
    alt: 'Reception photo 29',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-30',
    url: '/photos/reception/preview/MPPF-461.jpg',
    thumbnailUrl: '/photos/reception/thumbs/MPPF-461.jpg',
    alt: 'Reception photo 30',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-31',
    url: '/photos/reception/preview/IMG_0198.jpg',
    thumbnailUrl: '/photos/reception/thumbs/IMG_0198.jpg',
    alt: 'Reception photo 31',
    event: 'reception',
    date: 'Feb 10, 2026',
    isHighlight: true
  },
  {
    id: 'rec-32',
    url: '/photos/reception/preview/IMG_0199.jpg',
    thumbnailUrl: '/photos/reception/thumbs/IMG_0199.jpg',
    alt: 'Reception photo 32',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
  {
    id: 'rec-33',
    url: '/photos/reception/preview/IMG_0200.jpg',
    thumbnailUrl: '/photos/reception/thumbs/IMG_0200.jpg',
    alt: 'Reception photo 33',
    event: 'reception',
    date: 'Feb 10, 2026',
  },
];

export const ALBUMS: Album[] = [
  {
    id: 'family-portraits',
    title: 'Family Blessings',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFTGgZ5k9brmHDOGdTXUglgONzEyQtzAzRBZWGzio3xkfTEpe3O9pw0cPHoRLWto7p5l5o7l_LUyACExoTnSRQNtM8AbN2v9KDLlZhPyzkeat3eOdZqfQxJvFPXAxxQr5Lvqc9lxQSXZWk2G0PlpUgEbjK8CWKPqebCJxuRcVFNlyuCQoOiX2YUoQl8leivQs56OlH3jktJylwrx3d82u275AT1p7BemrEGdYIgozst-RPraAgzZPAEBwIJr313oPv-WoJ9VPofjto',
    eventId: 'ceremony',
    photoIds: ['c2', 'c3', 'c4', 'c5']
  },
  {
    id: 'bride-groom',
    title: 'Just the Two of Them',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGMqjzD-ns1ky6SYvp-vgbUknqbUaYW61sXRAsFd_NLF9JDgMcbu66aGbi8-TadgzrDDA8Ac2cJzkt0MCXAib4XqN8lJKC6ffCNijf6o4h58Gc1Kz71a3AMGZ_8fqFAcdENw_nAdPzK5-QCFbFzM1r3mrX-IAdVdT48nG7AjJmHAqlJJKAtRYYyx2HJ1cvOaQ8jaTlaQp2qde5wL2b_rVKWG7e2iFfqcmtx3USmwr5eVBY0SlvsUhX7LqvzTfPOdFgHALuhDRyC_Ab',
    eventId: 'ceremony',
    photoIds: ['c1', 'c6']
  },
  {
    id: 'haldi-moments',
    title: 'Turmeric & Laughter',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuANx0TDDqSu2q-2Q2Hf0qjmvsa2JlQO09lIaGGZw6C8sPxPVOKh3i6UV3akEFmT0z8g5yNlkKOWFR1gTTyFHUH9XtaT8rpSkWUgoogXjVG7WLkJrXpti7hXfYUC_pK1IZ2bk0B_cuFaIqUe6HjHg3M7jhsI9GE44Vs7m43rVcdHkZLi9fXSTyHFfjXzAzXHfdd_y8cWy4WdBQOAr-HGxdw2uY83Vhza5XK_TAb-dGmQVjVUf0255c3gqc6u-CEw7xTzs_4ODa97zlR-',
    eventId: 'haldi',
    photoIds: ['h1', 'h2', 'h3', 'h4']
  },
  {
    id: 'dance-floor',
    title: 'Pre-Wedding Portraits',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGsiYLxfLctKBonf6F-PZdhnFAAL_j_tNDN6PRI_OFpb0oLutAGDh1KIf6bFDDP6xvmChzmVdBcqm4bI7cAwCbgbbsZCCbfYyMRfjtX0qh8hyws-nURUpraUGjomNQUjWiXXo_Jb1WCtwKqCDfCOfALu7AWlLdeqmrhWCby5dJa4qkr1KXJmwwg34XUvh2FsH39fJ4ykTgudbmL6FvpGRY_4kPxW5WbWkpIYnyNd3qt3Vtx48ZL4qdh5utlc1Q6FYZcuMFf7IS96sa',
    eventId: 'prewedding',
    photoIds: ['s1', 's2', 's3']
  }
];
